// <auto-generated />
namespace FFCJardinagens.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Changeitbacktoin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changeitbacktoin));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121850461_Change it back to in"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
